name: dart_tutorial
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  calculator: 
    path: 'packages/calculator'

dev_dependencies:
  lints: ^1.0.0
  pedantic: ^1.11.1

